main: com.dfsek.betterEnd.Main
name: BetterEnd
version: 1.1.4
author: dfsek
description: Overhauls the End dimension with new biomes, structures, and more!
load: startup
depend: [WorldEdit]
api-version: 1.15
commands:
    betterend:
       description: BetterEnd base command
       usage: /betterend <biome|tpbiome|version>
       aliases: [be, end]
       permission: betterend.command
       permission-message: You don't have permission.